[
  {:listReadableFormats, 0, 0, ""},
  {:listReadableFilters, 1, 0, ""},
  {:listWritableFormats, 2, 0, ""},
  {:listWritableFilters, 3, 0, ""},
  {:archive_read_new, 4, 0, ""},
  {:archive_write_new, 5, 0, ""},
  {:archive_read_disk_new, 6, 0, ""},
  {:archive_write_disk_new, 7, 0, ""},
  {:archive_match_new, 8, 0, ""},
  {:archive_entry_new, 9, 0, ""},
  {:archive_entry_new2, 10, 1, "a: beam.term"},
  {:archive_entry_clone, 11, 1, "e: ArchiveEntryResource"},
  {:archive_entry_clear, 12, 1, "e: ArchiveEntryResource"},
  {:archive_entry_free, 13, 1, "e: ArchiveEntryResource"},
  {:archive_free, 14, 1, "a: beam.term"},
  {:archive_read_free, 15, 1, "a: beam.term"},
  {:archive_write_free, 16, 1, "a: beam.term"},
  {:archive_match_free, 17, 1, "a: beam.term"},
  {:archive_read_finish, 18, 1, "a: beam.term"},
  {:archive_write_finish, 19, 1, "a: beam.term"},
  {:archive_read_refresh, 20, 1, "a: beam.term"},
  {:archive_write_refresh, 21, 1, "a: beam.term"},
  {:archive_read_open_memory, 22, 2, "a: beam.term, data: []const u8"},
  {:archive_read_open_memory2, 23, 3, "a: beam.term, data: []const u8, read_size: usize"},
  {:archive_write_open_memory, 24, 2, "a: beam.term, capacity: usize"},
  {:archive_write_memory, 25, 1, "a: beam.term"},
  {:archive_read_next_header, 26, 2, "a: beam.term, e: ArchiveEntryResource"},
  {:archive_read_next_header2, 27, 2, "a: beam.term, e: ArchiveEntryResource"},
  {:archive_read_data, 28, 2, "a: beam.term, size: usize"},
  {:archive_read_data_block, 29, 1, "a: beam.term"},
  {:archive_write_data, 30, 2, "a: beam.term, data: []const u8"},
  {:archive_write_data_block, 31, 3, "a: beam.term, data: []const u8, offset: i64"},
  {:archive_seek_data, 32, 3, "a: beam.term, offset: i64, whence: c_int"},
  {:archive_read_extract2, 33, 3, "a: beam.term, e: ArchiveEntryResource, dest: beam.term"},
  {:archive_set_error, 34, 3, "a: beam.term, code: c_int, message: []const u8"},
  {:archive_entry_fflags, 35, 1, "e: ArchiveEntryResource"},
  {:archive_entry_mac_metadata, 36, 1, "e: ArchiveEntryResource"},
  {:archive_entry_copy_mac_metadata, 37, 2, "e: ArchiveEntryResource, data: []const u8"},
  {:archive_entry_digest, 38, 2, "e: ArchiveEntryResource, kind: c_int"},
  {:archive_entry_set_digest, 39, 3, "e: ArchiveEntryResource, kind: c_int, data: []const u8"},
  {:archive_entry_xattr_add_entry, 40, 3, "e: ArchiveEntryResource, name: []const u8, data: []const u8"},
  {:archive_entry_xattr_next, 41, 1, "e: ArchiveEntryResource"},
  {:archive_entry_sparse_next, 42, 1, "e: ArchiveEntryResource"},
  {:archive_entry_acl_next, 43, 2, "e: ArchiveEntryResource, want: c_int"},
  {:archive_entry_acl_to_text, 44, 2, "e: ArchiveEntryResource, flags: c_int"},
  {:archive_entry_acl_to_text_w, 45, 2, "e: ArchiveEntryResource, flags: c_int"},
  {:archive_match_path_unmatched_inclusions_next, 46, 1, "a: beam.term"},
  {:archive_match_path_unmatched_inclusions_next_w, 47, 1, "a: beam.term"},
  {:archive_read_disk_entry_from_file, 48, 3, "a: beam.term, e: ArchiveEntryResource, fd: c_int"},
  {:archive_read_disk_set_matching, 49, 2, "a: beam.term, matching: beam.term"},
  {:getExtractInfo, 50, 0, ""},
  {:extractFlagToInt, 51, 1, "f: ExtractFlag"},
  {:archiveFilterToInt, 52, 1, "f: ArchiveFilter"},
  {:archiveFormatToInt, 53, 1, "f: ArchiveFormat"},
  {:archiveFilterToAtom, 54, 1, "code: c_int"},
  {:archiveFormatToAtom, 55, 1, "code: c_int"},
  {:isSubFormatOf, 56, 2, "self: ArchiveFormat, parent: ArchiveFormat"},
  {:fileKinds, 57, 0, ""},
  {:archive_entry_copy_stat, 58, 2, "e: ArchiveEntryResource, stat: Stat"},
  {:archive_entry_stat, 59, 1, "e: ArchiveEntryResource"},
  {:archive_read_generation, 60, 1, "a: beam.term"},
  {:archive_entry_linkresolver_new, 61, 0, ""},
  {:archive_entry_linkresolver_free, 62, 1, "r: ArchiveLinkResource"},
  {:archive_entry_linkresolver_set_strategy, 63, 2, "r: ArchiveLinkResource, format: c_int"},
  {:archive_entry_linkify, 64, 2, "r: ArchiveLinkResource, e: ?ArchiveEntryResource"},
  {:archive_entry_partial_links, 65, 1, "r: ArchiveLinkResource"},
  {:archive_read_open_filenames, 66, 3, "a: beam.term, filenames: []const beam.term, block_size: usize"},
  {:archive_read_open_filenames_w, 67, 3, "a: beam.term, filenames: []const beam.term, block_size: usize"},
  {:archive_utility_string_sort, 68, 1, "values: []const beam.term"},
  {:archive_read_support_filter_program_signature, 69, 3, "a: beam.term, command: []const u8, signature: []const u8"},
  {:archive_read_support_compression_program_signature, 70, 3, "a: beam.term, command: []const u8, signature: []const u8"},
  {:archive_read_append_filter_program_signature, 71, 3, "a: beam.term, command: []const u8, signature: []const u8"},
  {:canonical_path, 72, 1, "path: []const u8"},
  {:archive_entry_copy_fflags_text_len, 73, 2, "e: ArchiveEntryResource, text: []const u8"},
  {:archive_bzlib_version, 74, 0, ""},
  {:archive_clear_error, 75, 1, "a0: beam.term"},
  {:archive_cng_version, 76, 0, ""},
  {:archive_commoncrypto_version, 77, 0, ""},
  {:archive_compression, 78, 1, "a0: beam.term"},
  {:archive_compression_name, 79, 1, "a0: beam.term"},
  {:archive_copy_error, 80, 2, "a0: beam.term, a1: beam.term"},
  {:archive_entry_acl_add_entry, 81, 6, "a0: ArchiveEntryResource, a1: c_int, a2: c_int, a3: c_int, a4: c_int, a5: ?[]const u8"},
  {:archive_entry_acl_add_entry_w, 82, 6, "a0: ArchiveEntryResource, a1: c_int, a2: c_int, a3: c_int, a4: c_int, a5: ?[]const u8"},
  {:archive_entry_acl_clear, 83, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_acl_count, 84, 2, "a0: ArchiveEntryResource, a1: c_int"},
  {:archive_entry_acl_from_text, 85, 3, "a0: ArchiveEntryResource, a1: []const u8, a2: c_int"},
  {:archive_entry_acl_from_text_w, 86, 3, "a0: ArchiveEntryResource, a1: []const u8, a2: c_int"},
  {:archive_entry_acl_reset, 87, 2, "a0: ArchiveEntryResource, a1: c_int"},
  {:archive_entry_acl_text, 88, 2, "a0: ArchiveEntryResource, a1: c_int"},
  {:archive_entry_acl_text_w, 89, 2, "a0: ArchiveEntryResource, a1: c_int"},
  {:archive_entry_acl_types, 90, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_atime, 91, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_atime_is_set, 92, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_atime_nsec, 93, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_birthtime, 94, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_birthtime_is_set, 95, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_birthtime_nsec, 96, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_copy_fflags_text, 97, 2, "a0: ArchiveEntryResource, a1: []const u8"},
  {:archive_entry_copy_fflags_text_w, 98, 2, "a0: ArchiveEntryResource, a1: []const u8"},
  {:archive_entry_copy_gname, 99, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_gname_w, 100, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_hardlink, 101, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_hardlink_w, 102, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_link, 103, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_link_w, 104, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_pathname, 105, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_pathname_w, 106, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_sourcepath, 107, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_sourcepath_w, 108, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_symlink, 109, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_symlink_w, 110, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_uname, 111, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_copy_uname_w, 112, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_ctime, 113, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_ctime_is_set, 114, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_ctime_nsec, 115, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_dev, 116, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_dev_is_set, 117, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_devmajor, 118, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_devminor, 119, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_fflags_text, 120, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_filetype, 121, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_filetype_is_set, 122, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_gid, 123, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_gid_is_set, 124, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_gname, 125, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_gname_utf8, 126, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_gname_w, 127, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_hardlink, 128, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_hardlink_is_set, 129, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_hardlink_utf8, 130, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_hardlink_w, 131, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_ino, 132, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_ino64, 133, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_ino_is_set, 134, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_is_data_encrypted, 135, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_is_encrypted, 136, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_is_metadata_encrypted, 137, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_mode, 138, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_mtime, 139, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_mtime_is_set, 140, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_mtime_nsec, 141, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_nlink, 142, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_pathname, 143, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_pathname_utf8, 144, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_pathname_w, 145, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_perm, 146, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_perm_is_set, 147, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_rdev, 148, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_rdev_is_set, 149, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_rdevmajor, 150, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_rdevminor, 151, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_set_atime, 152, 3, "a0: ArchiveEntryResource, a1: i64, a2: c_long"},
  {:archive_entry_set_birthtime, 153, 3, "a0: ArchiveEntryResource, a1: i64, a2: c_long"},
  {:archive_entry_set_ctime, 154, 3, "a0: ArchiveEntryResource, a1: i64, a2: c_long"},
  {:archive_entry_set_dev, 155, 2, "a0: ArchiveEntryResource, a1: c.dev_t"},
  {:archive_entry_set_devmajor, 156, 2, "a0: ArchiveEntryResource, a1: c.dev_t"},
  {:archive_entry_set_devminor, 157, 2, "a0: ArchiveEntryResource, a1: c.dev_t"},
  {:archive_entry_set_fflags, 158, 3, "a0: ArchiveEntryResource, a1: c_ulong, a2: c_ulong"},
  {:archive_entry_set_filetype, 159, 2, "a0: ArchiveEntryResource, a1: c_uint"},
  {:archive_entry_set_gid, 160, 2, "a0: ArchiveEntryResource, a1: i64"},
  {:archive_entry_set_gname, 161, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_gname_utf8, 162, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_hardlink, 163, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_hardlink_utf8, 164, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_ino, 165, 2, "a0: ArchiveEntryResource, a1: i64"},
  {:archive_entry_set_ino64, 166, 2, "a0: ArchiveEntryResource, a1: i64"},
  {:archive_entry_set_is_data_encrypted, 167, 2, "a0: ArchiveEntryResource, a1: u8"},
  {:archive_entry_set_is_metadata_encrypted, 168, 2, "a0: ArchiveEntryResource, a1: u8"},
  {:archive_entry_set_link, 169, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_link_to_hardlink, 170, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_set_link_to_symlink, 171, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_set_link_utf8, 172, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_mode, 173, 2, "a0: ArchiveEntryResource, a1: c.mode_t"},
  {:archive_entry_set_mtime, 174, 3, "a0: ArchiveEntryResource, a1: i64, a2: c_long"},
  {:archive_entry_set_nlink, 175, 2, "a0: ArchiveEntryResource, a1: c_uint"},
  {:archive_entry_set_pathname, 176, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_pathname_utf8, 177, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_perm, 178, 2, "a0: ArchiveEntryResource, a1: c.mode_t"},
  {:archive_entry_set_rdev, 179, 2, "a0: ArchiveEntryResource, a1: c.dev_t"},
  {:archive_entry_set_rdevmajor, 180, 2, "a0: ArchiveEntryResource, a1: c.dev_t"},
  {:archive_entry_set_rdevminor, 181, 2, "a0: ArchiveEntryResource, a1: c.dev_t"},
  {:archive_entry_set_size, 182, 2, "a0: ArchiveEntryResource, a1: i64"},
  {:archive_entry_set_symlink, 183, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_symlink_type, 184, 2, "a0: ArchiveEntryResource, a1: c_int"},
  {:archive_entry_set_symlink_utf8, 185, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_uid, 186, 2, "a0: ArchiveEntryResource, a1: i64"},
  {:archive_entry_set_uname, 187, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_set_uname_utf8, 188, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_size, 189, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_size_is_set, 190, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_sourcepath, 191, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_sourcepath_w, 192, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_sparse_add_entry, 193, 3, "a0: ArchiveEntryResource, a1: i64, a2: i64"},
  {:archive_entry_sparse_clear, 194, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_sparse_count, 195, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_sparse_reset, 196, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_strmode, 197, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_symlink, 198, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_symlink_type, 199, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_symlink_utf8, 200, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_symlink_w, 201, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_uid, 202, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_uid_is_set, 203, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_uname, 204, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_uname_utf8, 205, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_uname_w, 206, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_unset_atime, 207, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_unset_birthtime, 208, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_unset_ctime, 209, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_unset_mtime, 210, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_unset_size, 211, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_update_gname_utf8, 212, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_update_hardlink_utf8, 213, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_update_link_utf8, 214, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_update_pathname_utf8, 215, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_update_symlink_utf8, 216, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_update_uname_utf8, 217, 2, "a0: ArchiveEntryResource, a1: ?[]const u8"},
  {:archive_entry_xattr_clear, 218, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_xattr_count, 219, 1, "a0: ArchiveEntryResource"},
  {:archive_entry_xattr_reset, 220, 1, "a0: ArchiveEntryResource"},
  {:archive_errno, 221, 1, "a0: beam.term"},
  {:archive_error_string, 222, 1, "a0: beam.term"},
  {:archive_file_count, 223, 1, "a0: beam.term"},
  {:archive_filter_bytes, 224, 2, "a0: beam.term, a1: c_int"},
  {:archive_filter_code, 225, 2, "a0: beam.term, a1: c_int"},
  {:archive_filter_count, 226, 1, "a0: beam.term"},
  {:archive_filter_name, 227, 2, "a0: beam.term, a1: c_int"},
  {:archive_format, 228, 1, "a0: beam.term"},
  {:archive_format_name, 229, 1, "a0: beam.term"},
  {:archive_libacl_version, 230, 0, ""},
  {:archive_libattr_version, 231, 0, ""},
  {:archive_libbsdxml_version, 232, 0, ""},
  {:archive_libexpat_version, 233, 0, ""},
  {:archive_libiconv_version, 234, 0, ""},
  {:archive_liblz4_version, 235, 0, ""},
  {:archive_liblzma_version, 236, 0, ""},
  {:archive_liblzo2_version, 237, 0, ""},
  {:archive_libmd_version, 238, 0, ""},
  {:archive_libpcre2_version, 239, 0, ""},
  {:archive_libpcre_version, 240, 0, ""},
  {:archive_librichacl_version, 241, 0, ""},
  {:archive_libxml2_version, 242, 0, ""},
  {:archive_libzstd_version, 243, 0, ""},
  {:archive_match_exclude_entry, 244, 3, "a0: beam.term, a1: c_int, a2: ArchiveEntryResource"},
  {:archive_match_exclude_pattern, 245, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_exclude_pattern_from_file, 246, 3, "a0: beam.term, a1: []const u8, a2: c_int"},
  {:archive_match_exclude_pattern_from_file_w, 247, 3, "a0: beam.term, a1: []const u8, a2: c_int"},
  {:archive_match_exclude_pattern_w, 248, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_excluded, 249, 2, "a0: beam.term, a1: ArchiveEntryResource"},
  {:archive_match_include_date, 250, 3, "a0: beam.term, a1: c_int, a2: []const u8"},
  {:archive_match_include_date_w, 251, 3, "a0: beam.term, a1: c_int, a2: []const u8"},
  {:archive_match_include_file_time, 252, 3, "a0: beam.term, a1: c_int, a2: []const u8"},
  {:archive_match_include_file_time_w, 253, 3, "a0: beam.term, a1: c_int, a2: []const u8"},
  {:archive_match_include_gid, 254, 2, "a0: beam.term, a1: i64"},
  {:archive_match_include_gname, 255, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_include_gname_w, 256, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_include_pattern, 257, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_include_pattern_from_file, 258, 3, "a0: beam.term, a1: []const u8, a2: c_int"},
  {:archive_match_include_pattern_from_file_w, 259, 3, "a0: beam.term, a1: []const u8, a2: c_int"},
  {:archive_match_include_pattern_w, 260, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_include_time, 261, 4, "a0: beam.term, a1: c_int, a2: i64, a3: c_long"},
  {:archive_match_include_uid, 262, 2, "a0: beam.term, a1: i64"},
  {:archive_match_include_uname, 263, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_include_uname_w, 264, 2, "a0: beam.term, a1: []const u8"},
  {:archive_match_owner_excluded, 265, 2, "a0: beam.term, a1: ArchiveEntryResource"},
  {:archive_match_path_excluded, 266, 2, "a0: beam.term, a1: ArchiveEntryResource"},
  {:archive_match_path_unmatched_inclusions, 267, 1, "a0: beam.term"},
  {:archive_match_set_inclusion_recursion, 268, 2, "a0: beam.term, a1: c_int"},
  {:archive_match_time_excluded, 269, 2, "a0: beam.term, a1: ArchiveEntryResource"},
  {:archive_mbedtls_version, 270, 0, ""},
  {:archive_nettle_version, 271, 0, ""},
  {:archive_openssl_version, 272, 0, ""},
  {:archive_parse_date, 273, 2, "a0: i64, a1: []const u8"},
  {:archive_position_compressed, 274, 1, "a0: beam.term"},
  {:archive_position_uncompressed, 275, 1, "a0: beam.term"},
  {:archive_read_add_passphrase, 276, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_append_filter, 277, 2, "a0: beam.term, a1: c_int"},
  {:archive_read_append_filter_program, 278, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_close, 279, 1, "a0: beam.term"},
  {:archive_read_data_into_fd, 280, 2, "a0: beam.term, a1: c_int"},
  {:archive_read_data_skip, 281, 1, "a0: beam.term"},
  {:archive_read_disk_can_descend, 282, 1, "a0: beam.term"},
  {:archive_read_disk_current_filesystem, 283, 1, "a0: beam.term"},
  {:archive_read_disk_current_filesystem_is_remote, 284, 1, "a0: beam.term"},
  {:archive_read_disk_current_filesystem_is_synthetic, 285, 1, "a0: beam.term"},
  {:archive_read_disk_descend, 286, 1, "a0: beam.term"},
  {:archive_read_disk_gname, 287, 2, "a0: beam.term, a1: i64"},
  {:archive_read_disk_open, 288, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_disk_open_w, 289, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_disk_set_atime_restored, 290, 1, "a0: beam.term"},
  {:archive_read_disk_set_behavior, 291, 2, "a0: beam.term, a1: c_int"},
  {:archive_read_disk_set_standard_lookup, 292, 1, "a0: beam.term"},
  {:archive_read_disk_set_symlink_hybrid, 293, 1, "a0: beam.term"},
  {:archive_read_disk_set_symlink_logical, 294, 1, "a0: beam.term"},
  {:archive_read_disk_set_symlink_physical, 295, 1, "a0: beam.term"},
  {:archive_read_disk_uname, 296, 2, "a0: beam.term, a1: i64"},
  {:archive_read_extract, 297, 3, "a0: beam.term, a1: ArchiveEntryResource, a2: c_int"},
  {:archive_read_extract_set_skip_file, 298, 3, "a0: beam.term, a1: i64, a2: i64"},
  {:archive_read_format_capabilities, 299, 1, "a0: beam.term"},
  {:archive_read_has_encrypted_entries, 300, 1, "a0: beam.term"},
  {:archive_read_header_position, 301, 1, "a0: beam.term"},
  {:archive_read_open1, 302, 1, "a0: beam.term"},
  {:archive_read_open_fd, 303, 3, "a0: beam.term, a1: c_int, a2: usize"},
  {:archive_read_open_file, 304, 3, "a0: beam.term, a1: ?[]const u8, a2: usize"},
  {:archive_read_open_filename, 305, 3, "a0: beam.term, a1: ?[]const u8, a2: usize"},
  {:archive_read_open_filename_w, 306, 3, "a0: beam.term, a1: ?[]const u8, a2: usize"},
  {:archive_read_set_filter_option, 307, 4, "a0: beam.term, a1: ?[]const u8, a2: ?[]const u8, a3: ?[]const u8"},
  {:archive_read_set_format, 308, 2, "a0: beam.term, a1: c_int"},
  {:archive_read_set_format_option, 309, 4, "a0: beam.term, a1: ?[]const u8, a2: ?[]const u8, a3: ?[]const u8"},
  {:archive_read_set_option, 310, 4, "a0: beam.term, a1: ?[]const u8, a2: ?[]const u8, a3: ?[]const u8"},
  {:archive_read_set_options, 311, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_support_compression_all, 312, 1, "a0: beam.term"},
  {:archive_read_support_compression_bzip2, 313, 1, "a0: beam.term"},
  {:archive_read_support_compression_compress, 314, 1, "a0: beam.term"},
  {:archive_read_support_compression_gzip, 315, 1, "a0: beam.term"},
  {:archive_read_support_compression_lzip, 316, 1, "a0: beam.term"},
  {:archive_read_support_compression_lzma, 317, 1, "a0: beam.term"},
  {:archive_read_support_compression_none, 318, 1, "a0: beam.term"},
  {:archive_read_support_compression_program, 319, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_support_compression_rpm, 320, 1, "a0: beam.term"},
  {:archive_read_support_compression_uu, 321, 1, "a0: beam.term"},
  {:archive_read_support_compression_xz, 322, 1, "a0: beam.term"},
  {:archive_read_support_filter_all, 323, 1, "a0: beam.term"},
  {:archive_read_support_filter_by_code, 324, 2, "a0: beam.term, a1: c_int"},
  {:archive_read_support_filter_bzip2, 325, 1, "a0: beam.term"},
  {:archive_read_support_filter_compress, 326, 1, "a0: beam.term"},
  {:archive_read_support_filter_grzip, 327, 1, "a0: beam.term"},
  {:archive_read_support_filter_gzip, 328, 1, "a0: beam.term"},
  {:archive_read_support_filter_lrzip, 329, 1, "a0: beam.term"},
  {:archive_read_support_filter_lz4, 330, 1, "a0: beam.term"},
  {:archive_read_support_filter_lzip, 331, 1, "a0: beam.term"},
  {:archive_read_support_filter_lzma, 332, 1, "a0: beam.term"},
  {:archive_read_support_filter_lzop, 333, 1, "a0: beam.term"},
  {:archive_read_support_filter_none, 334, 1, "a0: beam.term"},
  {:archive_read_support_filter_program, 335, 2, "a0: beam.term, a1: []const u8"},
  {:archive_read_support_filter_rpm, 336, 1, "a0: beam.term"},
  {:archive_read_support_filter_uu, 337, 1, "a0: beam.term"},
  {:archive_read_support_filter_xz, 338, 1, "a0: beam.term"},
  {:archive_read_support_filter_zstd, 339, 1, "a0: beam.term"},
  {:archive_read_support_format_7zip, 340, 1, "a0: beam.term"},
  {:archive_read_support_format_all, 341, 1, "a0: beam.term"},
  {:archive_read_support_format_ar, 342, 1, "a0: beam.term"},
  {:archive_read_support_format_by_code, 343, 2, "a0: beam.term, a1: c_int"},
  {:archive_read_support_format_cab, 344, 1, "a0: beam.term"},
  {:archive_read_support_format_cpio, 345, 1, "a0: beam.term"},
  {:archive_read_support_format_empty, 346, 1, "a0: beam.term"},
  {:archive_read_support_format_gnutar, 347, 1, "a0: beam.term"},
  {:archive_read_support_format_iso9660, 348, 1, "a0: beam.term"},
  {:archive_read_support_format_lha, 349, 1, "a0: beam.term"},
  {:archive_read_support_format_mtree, 350, 1, "a0: beam.term"},
  {:archive_read_support_format_rar, 351, 1, "a0: beam.term"},
  {:archive_read_support_format_rar5, 352, 1, "a0: beam.term"},
  {:archive_read_support_format_raw, 353, 1, "a0: beam.term"},
  {:archive_read_support_format_tar, 354, 1, "a0: beam.term"},
  {:archive_read_support_format_warc, 355, 1, "a0: beam.term"},
  {:archive_read_support_format_xar, 356, 1, "a0: beam.term"},
  {:archive_read_support_format_zip, 357, 1, "a0: beam.term"},
  {:archive_read_support_format_zip_seekable, 358, 1, "a0: beam.term"},
  {:archive_read_support_format_zip_streamable, 359, 1, "a0: beam.term"},
  {:archive_version_details, 360, 0, ""},
  {:archive_version_number, 361, 0, ""},
  {:archive_version_string, 362, 0, ""},
  {:archive_wincrypt_version, 363, 0, ""},
  {:archive_write_add_filter, 364, 2, "a0: beam.term, a1: c_int"},
  {:archive_write_add_filter_b64encode, 365, 1, "a0: beam.term"},
  {:archive_write_add_filter_by_name, 366, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_add_filter_bzip2, 367, 1, "a0: beam.term"},
  {:archive_write_add_filter_compress, 368, 1, "a0: beam.term"},
  {:archive_write_add_filter_grzip, 369, 1, "a0: beam.term"},
  {:archive_write_add_filter_gzip, 370, 1, "a0: beam.term"},
  {:archive_write_add_filter_lrzip, 371, 1, "a0: beam.term"},
  {:archive_write_add_filter_lz4, 372, 1, "a0: beam.term"},
  {:archive_write_add_filter_lzip, 373, 1, "a0: beam.term"},
  {:archive_write_add_filter_lzma, 374, 1, "a0: beam.term"},
  {:archive_write_add_filter_lzop, 375, 1, "a0: beam.term"},
  {:archive_write_add_filter_none, 376, 1, "a0: beam.term"},
  {:archive_write_add_filter_program, 377, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_add_filter_uuencode, 378, 1, "a0: beam.term"},
  {:archive_write_add_filter_xz, 379, 1, "a0: beam.term"},
  {:archive_write_add_filter_zstd, 380, 1, "a0: beam.term"},
  {:archive_write_close, 381, 1, "a0: beam.term"},
  {:archive_write_disk_gid, 382, 3, "a0: beam.term, a1: []const u8, a2: i64"},
  {:archive_write_disk_set_options, 383, 2, "a0: beam.term, a1: c_int"},
  {:archive_write_disk_set_skip_file, 384, 3, "a0: beam.term, a1: i64, a2: i64"},
  {:archive_write_disk_set_standard_lookup, 385, 1, "a0: beam.term"},
  {:archive_write_disk_uid, 386, 3, "a0: beam.term, a1: []const u8, a2: i64"},
  {:archive_write_fail, 387, 1, "a0: beam.term"},
  {:archive_write_finish_entry, 388, 1, "a0: beam.term"},
  {:archive_write_get_bytes_in_last_block, 389, 1, "a0: beam.term"},
  {:archive_write_get_bytes_per_block, 390, 1, "a0: beam.term"},
  {:archive_write_header, 391, 2, "a0: beam.term, a1: ArchiveEntryResource"},
  {:archive_write_open_fd, 392, 2, "a0: beam.term, a1: c_int"},
  {:archive_write_open_file, 393, 2, "a0: beam.term, a1: ?[]const u8"},
  {:archive_write_open_filename, 394, 2, "a0: beam.term, a1: ?[]const u8"},
  {:archive_write_open_filename_w, 395, 2, "a0: beam.term, a1: ?[]const u8"},
  {:archive_write_set_bytes_in_last_block, 396, 2, "a0: beam.term, a1: c_int"},
  {:archive_write_set_bytes_per_block, 397, 2, "a0: beam.term, a1: c_int"},
  {:archive_write_set_compression_bzip2, 398, 1, "a0: beam.term"},
  {:archive_write_set_compression_compress, 399, 1, "a0: beam.term"},
  {:archive_write_set_compression_gzip, 400, 1, "a0: beam.term"},
  {:archive_write_set_compression_lzip, 401, 1, "a0: beam.term"},
  {:archive_write_set_compression_lzma, 402, 1, "a0: beam.term"},
  {:archive_write_set_compression_none, 403, 1, "a0: beam.term"},
  {:archive_write_set_compression_program, 404, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_set_compression_xz, 405, 1, "a0: beam.term"},
  {:archive_write_set_filter_option, 406, 4, "a0: beam.term, a1: ?[]const u8, a2: ?[]const u8, a3: ?[]const u8"},
  {:archive_write_set_format, 407, 2, "a0: beam.term, a1: c_int"},
  {:archive_write_set_format_7zip, 408, 1, "a0: beam.term"},
  {:archive_write_set_format_ar_bsd, 409, 1, "a0: beam.term"},
  {:archive_write_set_format_ar_svr4, 410, 1, "a0: beam.term"},
  {:archive_write_set_format_by_name, 411, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_set_format_cpio, 412, 1, "a0: beam.term"},
  {:archive_write_set_format_cpio_bin, 413, 1, "a0: beam.term"},
  {:archive_write_set_format_cpio_newc, 414, 1, "a0: beam.term"},
  {:archive_write_set_format_cpio_odc, 415, 1, "a0: beam.term"},
  {:archive_write_set_format_cpio_pwb, 416, 1, "a0: beam.term"},
  {:archive_write_set_format_filter_by_ext, 417, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_set_format_filter_by_ext_def, 418, 3, "a0: beam.term, a1: []const u8, a2: []const u8"},
  {:archive_write_set_format_gnutar, 419, 1, "a0: beam.term"},
  {:archive_write_set_format_iso9660, 420, 1, "a0: beam.term"},
  {:archive_write_set_format_mtree, 421, 1, "a0: beam.term"},
  {:archive_write_set_format_mtree_classic, 422, 1, "a0: beam.term"},
  {:archive_write_set_format_option, 423, 4, "a0: beam.term, a1: ?[]const u8, a2: ?[]const u8, a3: ?[]const u8"},
  {:archive_write_set_format_pax, 424, 1, "a0: beam.term"},
  {:archive_write_set_format_pax_restricted, 425, 1, "a0: beam.term"},
  {:archive_write_set_format_raw, 426, 1, "a0: beam.term"},
  {:archive_write_set_format_shar, 427, 1, "a0: beam.term"},
  {:archive_write_set_format_shar_dump, 428, 1, "a0: beam.term"},
  {:archive_write_set_format_ustar, 429, 1, "a0: beam.term"},
  {:archive_write_set_format_v7tar, 430, 1, "a0: beam.term"},
  {:archive_write_set_format_warc, 431, 1, "a0: beam.term"},
  {:archive_write_set_format_xar, 432, 1, "a0: beam.term"},
  {:archive_write_set_format_zip, 433, 1, "a0: beam.term"},
  {:archive_write_set_option, 434, 4, "a0: beam.term, a1: ?[]const u8, a2: ?[]const u8, a3: ?[]const u8"},
  {:archive_write_set_options, 435, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_set_passphrase, 436, 2, "a0: beam.term, a1: []const u8"},
  {:archive_write_set_skip_file, 437, 3, "a0: beam.term, a1: i64, a2: i64"},
  {:archive_write_zip_set_compression_bzip2, 438, 1, "a0: beam.term"},
  {:archive_write_zip_set_compression_deflate, 439, 1, "a0: beam.term"},
  {:archive_write_zip_set_compression_lzma, 440, 1, "a0: beam.term"},
  {:archive_write_zip_set_compression_store, 441, 1, "a0: beam.term"},
  {:archive_write_zip_set_compression_xz, 442, 1, "a0: beam.term"},
  {:archive_write_zip_set_compression_zstd, 443, 1, "a0: beam.term"},
  {:archive_zlib_version, 444, 0, ""},
  {:constants, 445, 0, ""},
  {:archive_read_data_current, 446, 3, "reader, generation, chunk_size"},
  {:archive_resource_probe, 447, 1, "diagnostic ownership probe; does not retain the native allocation"},
  {:archive_resource_stats, 448, 1, "diagnostic ownership probe; does not retain the native allocation"},
  {:archive_entry_read_generation, 449, 1, "entry; cursor generation captured atomically when reading the header"},
  {:archive_read_extract_current, 450, 4, "reader, generation, entry, flags; atomic cursor validation and extraction"},
]
