#!/usr/bin/env python3
"""Generate Rust dispatch from pinned C headers, audited operations and ownership adapters."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCALARS = {'int','unsigned int','unsigned long','long','char','size_t','la_int64_t','la_ssize_t','time_t','__LA_TIME_T','__LA_DEV_T','__LA_MODE_T','__LA_INO_T'}
STATUS_PREFIXES = ('archive_read_support','archive_read_set','archive_read_append','archive_read_open','archive_read_close','archive_read_data_','archive_read_extract','archive_write_set','archive_write_add','archive_write_zip','archive_write_open','archive_write_close','archive_write_finish','archive_write_disk_set','archive_read_disk_set','archive_read_disk_open','archive_read_disk_descend','archive_match_include','archive_match_exclude_','archive_match_set')
STATUS_NAMES = {'archive_entry_acl_add_entry','archive_entry_acl_add_entry_w','archive_entry_acl_from_text','archive_entry_acl_from_text_w','archive_write_header'}
NULLABLE = {'archive_entry_acl_add_entry','archive_entry_acl_add_entry_w','archive_read_open_filename','archive_read_open_filename_w','archive_read_open_file','archive_write_open_filename','archive_write_open_filename_w','archive_write_open_file'}

def normalize(s): return re.sub(r'\s+', ' ', s.replace('*', ' * ')).strip()
def declarations():
    result={}
    for path in sorted((ROOT/'vendor/libarchive').glob('*.h')):
        text=re.sub(r'/\*.*?\*/','',path.read_text(),flags=re.S)
        text=re.sub(r'^\s*#.*(?:\\\n.*)*','',text,flags=re.M)
        for decl in re.findall(r'__LA_DECL\s+([^;]+);',text):
            m=re.match(r'(.*?)\b(archive_\w+)\s*\((.*)\)',decl,re.S)
            if m:
                ret,name,args=m.groups()
                result[name]=(normalize(ret),[normalize(a) for a in args.split(',')] if args.strip()!='void' else [])
    return result

def nullable(name):
    return (name.startswith(('archive_entry_set_','archive_entry_copy_','archive_entry_update_')) and 'fflags_text' not in name) or name in NULLABLE or name.endswith(('_set_option','_set_format_option','_set_filter_option'))
def scalar(p):
    return next((s for s in sorted(SCALARS,key=len,reverse=True) if p==s or re.fullmatch(re.escape(s)+r' \w+',p)),None)
def archive_arg(name,i):
    if name.startswith('archive_match_'): kind='Some(Kind::Match)'
    elif name.startswith('archive_read_') or name=='archive_seek_data': kind='Some(Kind::Reader)'
    elif name.startswith('archive_write_'): kind='Some(Kind::Writer)'
    elif name in {'archive_errno','archive_error_string','archive_clear_error','archive_copy_error'}: kind='None'
    else: return f'ctx.io(args[{i}])?'
    return f'ctx.archive(args[{i}], {kind})?'

def wrapper(name,ret,params):
    prep=[];calls=[]
    for i,p in enumerate(params):
        if re.fullmatch(r'struct archive_entry \*(?: \w+)?',p): calls.append(f'ctx.entry(args[{i}])?')
        elif re.fullmatch(r'struct archive \*(?: \w+)?',p): calls.append(archive_arg(name,i))
        elif re.fullmatch(r'const (char|wchar_t) \*(?: \w+)?',p):
            fun,ptr=('wide','wptr') if 'wchar_t' in p else ('cstring','cptr')
            prep.append(f'let s{i} = {fun}(args[{i}], {str(nullable(name)).lower()})?;')
            calls.append(f'{ptr}(&s{i})')
        elif (s:=scalar(p)):
            if s in {'__LA_DEV_T','__LA_INO_T','__LA_MODE_T'}:
                alias={'__LA_DEV_T':'DEV','__LA_INO_T':'INO','__LA_MODE_T':'MODE'}[s]
                calls.append(f'args[{i}].decode::<ffi::ARCHIVE_BIND_{alias}_T>()?')
                continue
            unsigned=s.startswith('unsigned') or s in {'size_t','__LA_DEV_T','__LA_MODE_T','__LA_INO_T','char'}
            t='u64' if unsigned else 'i64'
            calls.append(f'args[{i}].decode::<{t}>()?.try_into().map_err(|_| Error::BadArg)?')
        else: return None
    call=f'ffi::{name}({", ".join(calls)})'
    if ret=='void': result=f'{call}; ok(ctx.env)'
    elif ret=='int' and (name.startswith(STATUS_PREFIXES) or name in STATUS_NAMES): result=f'status({call})?; ok(ctx.env)'
    elif ret in SCALARS: result=f'Ok({call}.encode(ctx.env))'
    elif ret=='const char *': result=f'string(ctx.env, {call})'
    elif ret=='const wchar_t *': result=f'wide_string(ctx.env, {call})'
    else: return None
    return '\n'.join(prep+[result])

def outputs():
    declarations_map=declarations()
    operations=json.loads((ROOT/'priv/operations.json').read_text())
    inventory=json.loads((ROOT/'priv/api_inventory.json').read_text())
    if set(inventory)!=set(declarations_map): raise SystemExit('Pinned header inventory changed; audit additions/exclusions first')
    src='// Generated by scripts/generate_bindings.py. Do not edit.\n// Integer conversions differ across the supported C ABIs.\n#![allow(clippy::useless_conversion, clippy::vec_init_then_push)]\nuse crate::*;\n'
    src+="pub(super) unsafe fn invoke<'a>(index: usize, args: &[Term<'a>], ctx: &mut Context<'a, '_, '_>) -> NifResult<Term<'a>> {\n    match index {\n"
    bindings=[]
    for op in operations:
        name=op['name'];index=op['index'];arity=op['arity']
        bindings.append(f'  {{:{name}, {index}, {arity}, "{op["signature"]}"}},\n')
        body=None
        if name in declarations_map and inventory[name]['kind']=='generated':
            body=wrapper(name,*declarations_map[name])
            if body is None: raise SystemExit(f'Missing ownership adapter for {name}')
        if body is None: body=f'adapters::invoke("{name}", args, ctx)'
        guard=f'args.len() != {arity}' if arity else '!args.is_empty()'
        src+=f'        {index} => {{ if {guard} {{ return Err(Error::BadArg); }} {body} }},\n'
    src+='        _ => Err(error("UnknownOperation")),\n    }\n}\n'
    tables=json.loads((ROOT/'priv/tables.json').read_text())
    src+='pub(super) fn enum_value(category: &str, name: &str) -> NifResult<i32> {\n match (category, name) {\n'
    for category,values in tables.items():
        if isinstance(values,dict):
            for name,c in values.items(): src+=f'("{category}", "{name}") => Ok(ffi::{c} as i32),\n'
    src+=' _ => Err(Error::BadArg) }\n}\n'
    src+='pub(super) fn enum_name(category: &str, value: i32) -> Option<&\'static str> {\n match (category, value) {\n'
    for category,values in tables.items():
        if isinstance(values,dict):
            for name,c in values.items(): src+=f'("{category}", n) if n == ffi::{c} as i32 => Some("{name}"),\n'
    src+=' _ => None }\n}\n'
    src+='pub(super) fn table_names(category: &str, write: bool) -> Vec<&\'static str> { match (category, write) {\n'
    for category,key in [('ArchiveFormat','archive_format_info'),('ArchiveFilter','archive_filter_info')]:
        for write in [False,True]:
            names=[name for name,allow in tables[key] if allow in (['Write','ReadWrite'] if write else ['Read','ReadWrite'])]
            src+=f'("{category}", {str(write).lower()}) => vec!{json.dumps(names)},\n'
    src+=' _ => vec![] } }\n'
    src+="pub(super) fn extract_docs<'a>(env: Env<'a>) -> NifResult<Term<'a>> { let mut result = Vec::new();\n"
    for name,doc in tables['extract_docs']:
        src+=f'result.push(map(env, &[("flag", atom(env, "{name}")?), ("default_doc", {json.dumps(doc)}.encode(env))])?);\n'
    src+='Ok(result.encode(env)) }\n'
    headers='\n'.join(p.read_text() for p in (ROOT/'vendor/libarchive').glob('*.h'))
    names=set(re.findall(r'^#define\s+((?:ARCHIVE_|AE_)[A-Z0-9_]+)\s+',headers,re.M))
    names=sorted(n for n in names if not any(tag in n for tag in ('INCLUDED','VERSION','H_INCLUDED')))
    src+="pub(super) fn constants<'a>(env: Env<'a>) -> NifResult<Term<'a>> { map(env, &[\n"
    for name in names: src+=f'("{name}", ffi::{name}.encode(env)),\n'
    src+=']) }\n'
    # Format through rustfmt so --check compares the actual committed Rust source.
    import subprocess
    src=subprocess.run(['rustup','run','1.95.0','rustfmt','--edition','2021'],input=src,text=True,capture_output=True,check=True).stdout
    return {'native/archive/src/generated.rs':src,'priv/bindings.exs':'[\n'+''.join(bindings)+']\n'}

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for filename,content in outputs().items():
        path=ROOT/filename
        if args.check:
            if not path.exists() or path.read_text()!=content: raise SystemExit(f'{filename} is stale')
        else: path.write_text(content)
    inventory=json.loads((ROOT/'priv/api_inventory.json').read_text())
    count=sum(x['kind']!='excluded' for x in inventory.values())
    print(f'{len(inventory)} declarations: {count} bound, {len(inventory)-count} excluded')
if __name__=='__main__':main()
